### ISSUE TITLE
Any way to add picture in the resume?

### ISSUE THREAD

**Issue by qwtsc** [ricosmall/jsonresume-theme-apage#4]
I cannot figure out how to add my picture in the resume with this theme, is there any possible way to do that? Maybe need another pr?

**Comment by ricosmall** [comment]
What is your purpose of adding picture to resume? Do you just want to show your avatar at the top of resume or other pictures of those projects you have done?

As I said at the top of [README.md](https://github.com/ricosmall/jsonresume-theme-apage/blob/master/README.md), the purpose of this theme is trying to fit all infomation in a print page which could make your resume brief enough. You should think twice that do you really want to insert pictures into  your resume but not just words.

**Comment by qwtsc** [comment]
![image](https://user-images.githubusercontent.com/34210641/86512701-ed7b1780-be36-11ea-9497-af390ef09eb3.png)
Just something like this, the "picture" I mean is the portrait photo that is used to give the first impression.

If you think it is not necessary for the resume, that's OK. I will just leave that feature in my fork. Thanks bro.

**Comment by qwtsc** [comment]
And it's time to close this issue :)

**Comment by ricosmall** [comment]
I think it’s okay, we can make it optional, what do you think?
your pr is welcomed if you finish the feature. And I will also think about the implementation.

**Comment by ricosmall** [comment]
@qwtsc Now you can add `avatar` filed in `basics`, and you will see the picture at the top of your resume page. If you have more advice, please give me feedback, thanks.
